### ISSUE TITLE
Conversion of pictures

### ISSUE THREAD

**Issue by tymurbaniak** [tymurbaniak/grotserv#4]
It would be good, if grot could convert and use other images than .bmp.

**Comment by tutajrobert** [comment]
Grot can use .png file instead of .bmp, but conversion from different image formats is really difficult in PIL package only. There are some problems with .jpg and .gif and without use of third party software or package like imagemagick I can't solve this issue. Additionaly, there will be much more to do if .jpg will be in RGBA, CMYK or even worse in some photoshop palette. Bitmap file is in 99% in RGB, so it's safe to use. It's hard to say, but I can't help with this enhancement. I recommend to check file format and warn the user to save it in .bmp or use different method (not PIL and python) to convert image.

**Comment by tymurbaniak** [comment]
Changing labels, since it's achievable in php without much difficulities.
